eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://netflix-eureka.cloudapps.nocosetest.com/eureka/v2/}
security:
  user:
    password: ${eureka.password}

---
spring:
  profiles: ose
eureka:
  client:
    healthcheck:
      enabled: false
  instance:
    metadata:
    nonSecurePort: 80
    preferIpAddress: ${USEHOSTNAME:false}
    hostname: ${APPHOSTNAME}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  password: ${EUREKA_USER_PASSWORD:password}